<div style="float:left; padding-right:16px;"><?php echo $this->gravatar($this->identity()->getEmail()) ?></div>
<h3><?php echo $this->translate('Hello'); ?>, <?php echo $this->identity()->getDisplayName() ?: $this->identity()->getUsername() ?: $this->identity()->getEmail() ?>!</h3>
<a href="<?php echo $this->url('zfcuser/logout') ?>">[<?php echo $this->translate('Sign Out'); ?>]</a>
<div style="clear:both;"></div>
